project:
  type: website
  output-dir: _output
  resources:
    - "*.qmd"

format:
  html:
    theme: superhero
    toc: true
    number-sections: true

website:
  title: "Money Talks: The Unspoken World of Market Manipulation"
  navbar:
    right:
      - text: "About Us"
        href: about_us.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/apa
